# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test(self):
    self.driver.get("http://localhost:5000/login")
    self.driver.set_window_size(1050, 670)
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("selenum@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("sele")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "Connect").click()
    self.driver.find_element(By.LINK_TEXT, "Add Post").click()
    self.driver.find_element(By.ID, "title").click()
    self.driver.find_element(By.ID, "title").send_keys("hi")
    self.driver.find_element(By.ID, "content").send_keys("post")
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-8 > .content-section").click()
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "hi").click()
    self.driver.find_element(By.LINK_TEXT, "Update").click()
    self.driver.find_element(By.ID, "content").click()
    self.driver.find_element(By.ID, "content").send_keys("post updated")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "Connect").click()
    self.driver.find_element(By.NAME, "q").click()
    self.driver.find_element(By.NAME, "q").send_keys("test")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-dark").click()
    self.driver.find_element(By.CSS_SELECTOR, ".media:nth-child(3) .mr-2").click()
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa").click()
    self.driver.find_element(By.LINK_TEXT, "Your Profile").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa").click()
    self.driver.find_element(By.LINK_TEXT, "Log Out").click()
  
