"""Added workout session model type

Revision ID: 0d788ba83f41
Revises: 0f901b03b058
Create Date: 2021-07-26 16:39:50.004448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d788ba83f41'
down_revision = '0f901b03b058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_session', sa.Column('type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_session', 'type')
    # ### end Alembic commands ###
