"""Added customer responded flag for exercise

Revision ID: 1bf22e75cabc
Revises: 1e4e243632fd
Create Date: 2021-08-04 14:27:11.261539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf22e75cabc'
down_revision = '1e4e243632fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('customer_responded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'customer_responded')
    # ### end Alembic commands ###
