"""empty message

Revision ID: 1e4e243632fd
Revises: 0080490a2907
Create Date: 2021-08-04 14:23:04.949763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e4e243632fd'
down_revision = '0080490a2907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_modifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('rep_modifier', sa.Integer(), nullable=True),
    sa.Column('set_modifier', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('exercise', sa.Column('unique_id_in_dict', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'unique_id_in_dict')
    op.drop_table('exercise_modifier')
    # ### end Alembic commands ###
