"""darkmode column

Revision ID: 856b026d87e8
Revises: 1bf22e75cabc
Create Date: 2021-08-05 08:15:38.766130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856b026d87e8'
down_revision = '1bf22e75cabc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('dark_mode', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'dark_mode')
    # ### end Alembic commands ###
