"""Added dark mode column

Revision ID: f2a4c1ecb862
Revises: 1bf22e75cabc
Create Date: 2021-08-05 21:16:00.530569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a4c1ecb862'
down_revision = '1bf22e75cabc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('dark_mode', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'dark_mode')
    # ### end Alembic commands ###
